version: "3"
services:
  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FirstCRUDApp
    volumes:
      - ./init_data:/docker-entrypoint-initdb.d
    restart: always
    tty: true



  custom_app:
    # build: .
    image: thespiritman/firstcrudapplication:latest
    container_name: firstcrudapp
    ports:
      - "5555:5555"
    depends_on:
      - db
    tty: true
    restart: always



volumes:
  init_data: 