apiVersion: v1
kind: Namespace
metadata:
  name: firstcrudapp

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deploy
  namespace: firstcrudapp
  labels:
    app: db
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      tier: backend
  template:
    metadata:
      labels:
        app: db
        tier: backend
    spec:
      containers:
      - name: db
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "FirstCRUDApp"
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - bash
            - "-c"
            - |
              mysqladmin -uroot -p$MYSQL_ROOT_PASSWORD ping &> /dev/null
          initialDelaySeconds: 10
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: firstcrudapp
  labels:
    tier: backend
spec:
  type: ClusterIP #default
  selector:
    app: db
    tier: backend
  ports:
  - name: db
    protocol: TCP
    port: 3306
    targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: firstcrudapp
  labels:
    app: frontend-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-app
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend-app
        tier: frontend
    spec:
      containers:
      - name: frontend-app
        image: thespiritman/firstcrudapplication:latest
        ports:
        - name: app-port
          containerPort: 5555
        livenessProbe:
          httpGet:
            path: /
            port: app-port
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 10
--- 
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: firstcrudapp
  labels:
    tier: frontend
spec:
  type: NodePort
  selector:
    app: frontend-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
    nodePort: 30001